#!/usr/bin/env python

import os
import json
from ed_helper_publisher.utilities import print_json

terraform_state_file = os.environ.get("TERRAFORM_STATE_FILE","terraform.tfstate")

with open(terraform_state_file) as json_file:
    data = json.load(json_file)

with open(terraform_state_file) as json_file:
    raw = json.load(json_file)

results = {}

for resource in data["resources"]:
    for instance in resource["instances"]:
        _type = resource["type"]
        # this is the main category for the terraform template
        if _type != "aws_eks_cluster": continue
        results = resource["instances"][0]["attributes"]

        _name = os.environ.get("EKS_CLUSTER")
        if not _name: _name = os.environ.get("EKS_NAME")
        if not _name: _name = os.environ.get("K8_NAME")
        if _name: results["name"] = _name

        results["_id"] = results["arn"].replace(":","_")
        results["id"] = results["_id"]
        #results["_id"] = "eks-{}".format(results["id"])

        try:
            region = results.get("arn").split(":")[3]
        except:
            region = None

        if not region: os.environ.get("AWS_DEFAULT_REGION")
        if region: results["region"] = region

        # should only be on eks
        break

results["raw"] = {}
results["raw"]["terraform"] = raw
results["provider"] = "aws"
results["resource_type"] = "eks"

print '_ed_begin_output'
print_json(results)
print '_ed_end_output'
